### ISSUE TITLE
Cors blocking

### ISSUE THREAD

**Issue by ghost** [kodbruket/vsf-payment-klarna#3]
Hi,

I thought this project would be more of a simple module. I followed the instructions, and when klarna did not display on checkout, I extracted all of the respective contents to each respective file and folder on a new vsf project, but encountered cors blocking any requests from the requested resource (Which is klarna in this case) upon checkout.

Has this project been tested on live production?

An idea is to create preflight guide https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS in your doc. The instructions are just plain commands and not really super instructive on what to do. 

Further on the contents in the repo is highly unorganised, making no sense of why the VSF project is linked inside your repo and there's another folder named API containing what I believe is your project containing the klarna API data and config file running on the default vsf port 8080.

Even following your commands will launch a vsf project but will not display any klarna checkout when adding products to shopping cart and checking out.

I recommend to add more detailed information, step by step on how to get klarna checkout working upon checkout with vsf. I would love to help but as of now I have a hard time understanding how to make this properly work upon checkout.

The only result i get upon checkout is "Loading".

**Comment by benjick** [comment]
@Decntdefalt Hey, can you the branch found in #5?

**Comment by benjick** [comment]
Sorry, should work a lot better now
